# Stubs for wsproto.utf8validator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Utf8Validator:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def validate(self, ba: Any): ...
