# Stubs for markdown.extensions.abbr (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import Extension
from ..inlinepatterns import Pattern
from ..preprocessors import Preprocessor
from ..util import AtomicString, etree
from typing import Any

ABBR_REF_RE: Any

class AbbrExtension(Extension):
    def extendMarkdown(self, md: Any, md_globals: Any) -> None: ...

class AbbrPreprocessor(Preprocessor):
    def run(self, lines: Any): ...

class AbbrPattern(Pattern):
    title: Any = ...
    def __init__(self, pattern: Any, title: Any) -> None: ...
    def handleMatch(self, m: Any): ...

def makeExtension(*args: Any, **kwargs: Any): ...
