# Stubs for markdown.extensions.meta (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import Extension
from ..preprocessors import Preprocessor
from typing import Any

log: Any
META_RE: Any
META_MORE_RE: Any
BEGIN_RE: Any
END_RE: Any

class MetaExtension(Extension):
    def extendMarkdown(self, md: Any, md_globals: Any) -> None: ...

class MetaPreprocessor(Preprocessor):
    def run(self, lines: Any): ...

def makeExtension(*args: Any, **kwargs: Any): ...
