# Stubs for markdown.extensions.smarty (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import Extension
from ..inlinepatterns import HTML_RE, HtmlPattern
from ..odict import OrderedDict
from ..treeprocessors import InlineProcessor
from typing import Any

punctClass: str
endOfWordClass: str
closeClass: str
openingQuotesBase: str
substitutions: Any
singleQuoteStartRe: Any
doubleQuoteStartRe: Any
doubleQuoteSetsRe: str
singleQuoteSetsRe: str
decadeAbbrRe: str
openingDoubleQuotesRegex: Any
closingDoubleQuotesRegex: str
closingDoubleQuotesRegex2: Any
openingSingleQuotesRegex: Any
closingSingleQuotesRegex: Any
closingSingleQuotesRegex2: Any
remainingSingleQuotesRegex: str
remainingDoubleQuotesRegex: str
HTML_STRICT_RE: Any

class SubstituteTextPattern(HtmlPattern):
    replace: Any = ...
    markdown: Any = ...
    def __init__(self, pattern: Any, replace: Any, markdown_instance: Any) -> None: ...
    def handleMatch(self, m: Any): ...

class SmartyExtension(Extension):
    config: Any = ...
    substitutions: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def educateDashes(self, md: Any) -> None: ...
    def educateEllipses(self, md: Any) -> None: ...
    def educateAngledQuotes(self, md: Any) -> None: ...
    def educateQuotes(self, md: Any) -> None: ...
    inlinePatterns: Any = ...
    def extendMarkdown(self, md: Any, md_globals: Any) -> None: ...

def makeExtension(*args: Any, **kwargs: Any): ...
