# Stubs for markdown.extensions.tables (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import Extension
from ..blockprocessors import BlockProcessor
from ..inlinepatterns import BACKTICK_RE, BacktickPattern
from ..util import etree
from typing import Any

class TableProcessor(BlockProcessor):
    def test(self, parent: Any, block: Any): ...
    def run(self, parent: Any, blocks: Any) -> None: ...

class TableExtension(Extension):
    def extendMarkdown(self, md: Any, md_globals: Any) -> None: ...

def makeExtension(*args: Any, **kwargs: Any): ...
