# Stubs for h11.tests.test_receivebuffer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .._receivebuffer import ReceiveBuffer

def test_receivebuffer() -> None: ...
