# Stubs for markdown.__main__ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

logger: Any

def parse_options(args: Optional[Any] = ..., values: Optional[Any] = ...): ...
def run() -> None: ...
