# Stubs for markdown.serializers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import util
from typing import Any

ElementTree = util.etree.ElementTree
QName = util.etree.QName
Comment = util.etree.Comment
ProcessingInstruction = util.etree.ProcessingInstruction

def to_html_string(element: Any): ...
def to_xhtml_string(element: Any): ...
