# Stubs for h11 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._connection import *
from ._events import *
from ._state import *
from ._util import LocalProtocolError as LocalProtocolError, ProtocolError as ProtocolError, RemoteProtocolError as RemoteProtocolError

# Names in __all__ with no definition:
#   CLIENT
#   CLOSED
#   Connection
#   ConnectionClosed
#   DONE
#   Data
#   ERROR
#   EndOfMessage
#   IDLE
#   InformationalResponse
#   MIGHT_SWITCH_PROTOCOL
#   MUST_CLOSE
#   NEED_DATA
#   PAUSED
#   Request
#   Response
#   SEND_BODY
#   SEND_RESPONSE
#   SERVER
#   SWITCHED_PROTOCOL
