# Stubs for h11._abnf (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

OWS: str
token: str
field_name = token
vchar: str
vchar_or_obs_text: str
field_vchar = vchar_or_obs_text
field_content: Any
field_value: Any
header_field: Any
method = token
request_target: Any
http_version: str
request_line: Any
status_code: str
reason_phrase: Any
status_line: Any
HEXDIG: str
chunk_size: Any
chunk_ext: str
chunk_header: Any
