# Stubs for parsedatetime.pdt_locales (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .icu import get_icu as get_icu
from typing import Any

def load_locale(locale: Any, icu: bool = ...): ...
