# Stubs for parsedatetime.pdt_locales.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

locale_keys: Any
localeID: Any
dateSep: Any
timeSep: Any
meridian: Any
usesMeridian: bool
uses24: bool
WeekdayOffsets: Any
MonthOffsets: Any
Weekdays: Any
shortWeekdays: Any
Months: Any
shortMonths: Any
dateFormats: Any
timeFormats: Any
dp_order: Any
numbers: Any
decimal_mark: str
units: Any
re_values: Any
Modifiers: Any
dayOffsets: Any
re_sources: Any
small: Any
magnitude: Any
ignore: Any
