# Stubs for parsedatetime.pdt_locales.en_AU (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from typing import Any

localeID: str
dateSep: Any
uses24: bool
dateFormats: Any
dp_order: Any
