# Stubs for parsedatetime.pdt_locales.nl_NL (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from typing import Any

localeID: str
dateSep: Any
timeSep: Any
meridian: Any
usesMeridian: bool
uses24: bool
decimal_mark: str
Weekdays: Any
shortWeekdays: Any
Months: Any
shortMonths: Any
dateFormats: Any
timeFormats: Any
dp_order: Any
units: Any
re_values: Any
Modifiers: Any
dayOffsets: Any
re_sources: Any
