# Stubs for parsedatetime.pdt_locales.pt_BR (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from typing import Any

localeID: str
dateSep: Any
usesMeridian: bool
uses24: bool
decimal_mark: str
Weekdays: Any
shortWeekdays: Any
Months: Any
shortMonths: Any
dateFormats: Any
timeFormats: Any
dp_order: Any
units: Any
