# Stubs for parsedatetime.pdt_locales.ru_RU (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from typing import Any

localeID: str
dateSep: Any
timeSep: Any
meridian: Any
usesMeridian: bool
uses24: bool
Weekdays: Any
shortWeekdays: Any
Months: Any
shortMonths: Any
dateFormats: Any
timeFormats: Any
dp_order: Any
decimal_mark: str
units: Any
re_values: Any
Modifiers: Any
dayOffsets: Any
re_sources: Any
small: Any
numbers: Any
magnitude: Any
